# Generated by Django 5.0 on 2024-01-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='phto',
            new_name='photo',
        ),
    ]
