# Generated by Django 5.0 on 2024-01-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_project_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(blank=True, max_length=99, null=True)),
                ('buyer_username', models.CharField(blank=True, max_length=99, null=True)),
                ('buyer_email', models.CharField(blank=True, max_length=99, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=99, null=True)),
                ('seller_username', models.CharField(blank=True, max_length=99, null=True)),
                ('seller_email', models.CharField(blank=True, max_length=99, null=True)),
                ('type', models.CharField(blank=True, max_length=99, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('project', models.CharField(blank=True, max_length=99, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
